clean:
	rm -rf __pycache__/ solution.pl prolog_result.txt *.out *put.txt *.pl

sudoku:
	python3 validator.py --stdio zad4 python3 sudoku.py

zad1:
	python3 validator.py zad1 python3 zad1.py

zad2:
	python3 validator.py zad2 python3 zad2.py

storms:
	python3 validator.py zad5 python3 storms_for_students.py